// url=https://www.figma.com/design/rL6ZmEg0OhxMPuvQmtpNH8/Hearth-%E2%80%94-HT-Design-System?node-id=22-21
// source=design-systems/hearth/components/surfaces/MetricCard.jsx
// component=MetricCard
//
// Figma's Tone variant has a third, unnamed draft option ("Tone3" —
// an autogenerated placeholder, see figma-todo.md) with no code
// counterpart. Deliberately left out of the mapping below rather than
// guessing a value; instances using it will emit variant={undefined}.
import figma from 'figma'
const instance = figma.selectedInstance

const value = instance.getString('Number')
const label = instance.getString('Label')
const variant = instance.getEnum('Tone', {
  Default: 'default',
  Warning: 'warn',
})

export default {
  example: figma.code`
    <MetricCard
      value="${value}"
      label="${label}"
      ${variant === 'warn' ? 'variant="warn"' : ''}
    />
  `,
  imports: ["import { MetricCard } from './MetricCard.jsx'"],
  id: 'metric-card',
  metadata: { nestable: true },
}
